package models;

public enum CardID {
		SPELLTRAPZONE, 
		GRAVEYARD, 
		DECKZONE, 
		CARDBACK, 
		
		MONSTER_WHITEDRAGONWITHBLUEEYES,
		MONSTER_MAGONEGRO,
		MONSTER_MYSTICALELF,
		MONSTER_THEALLSEEINGWHITETIGER,
		MONSTER_GIANTSOLDIEROFSTONE,
		
		MAGIC_DARKHOLE,
		MAGIC_FINALFLAME,
		MAGIC_FISSURE,
		MAGIC_DIANKETOTHECUREMASTER,
		
		TRAP_CASTTLEWALLS,
		TRAP_REVERSETRAP
	
}

